#backend = "Windows WASAPI"
backend = "Windows WDM-KS"
bufferSizeSamples = 512
[input]
device = "マイク (JUMBLEQ)"
channels = 4
sampleType = "Int24"
wasapiExclusiveMode = false
wasapiAutoConvert = true
[output]
#device = "スピーカー (JUMBLEQ)"
device = "Speakers (JUMBLEQ)"
channels = 4
sampleType = "Int24"
wasapiAutoConvert = true
wasapiExclusiveMode = false
